/* tslint:disable */
/* eslint-disable */
/**
 * Financial API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IncomeCategoryDto } from './IncomeCategoryDto';
import {
    IncomeCategoryDtoFromJSON,
    IncomeCategoryDtoFromJSONTyped,
    IncomeCategoryDtoToJSON,
} from './IncomeCategoryDto';

/**
 * 
 * @export
 * @interface IncomeDto
 */
export interface IncomeDto {
    /**
     * 
     * @type {number}
     * @memberof IncomeDto
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof IncomeDto
     */
    ownerId?: number;
    /**
     * 
     * @type {string}
     * @memberof IncomeDto
     */
    amount?: string;
    /**
     * 
     * @type {string}
     * @memberof IncomeDto
     */
    currency?: string;
    /**
     * 
     * @type {Date}
     * @memberof IncomeDto
     */
    date?: Date;
    /**
     * 
     * @type {IncomeCategoryDto}
     * @memberof IncomeDto
     */
    incomeCategory?: IncomeCategoryDto;
}

/**
 * Check if a given object implements the IncomeDto interface.
 */
export function instanceOfIncomeDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IncomeDtoFromJSON(json: any): IncomeDto {
    return IncomeDtoFromJSONTyped(json, false);
}

export function IncomeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncomeDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'ownerId': !exists(json, 'ownerId') ? undefined : json['ownerId'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'currency': !exists(json, 'currency') ? undefined : json['currency'],
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
        'incomeCategory': !exists(json, 'incomeCategory') ? undefined : IncomeCategoryDtoFromJSON(json['incomeCategory']),
    };
}

export function IncomeDtoToJSON(value?: IncomeDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'ownerId': value.ownerId,
        'amount': value.amount,
        'currency': value.currency,
        'date': value.date === undefined ? undefined : (value.date.toISOString().substring(0,10)),
        'incomeCategory': IncomeCategoryDtoToJSON(value.incomeCategory),
    };
}

